apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: dev
data:
  APP_ENV: dev
  APP_PORT: "8000"
  LOG_LEVEL: info
  DB_HOST: postgres-dev-postgresql.dev.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: kbs-admin
  DB_NAME: my-db