apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: prod
type: Opaque
data:
  password: cHJvZC1wYXNzd29yZC00NTY=
  postgres-password: cHJvZC1wYXNzd29yZC00NTY=
  replication-password: cHJvZC1wYXNzd29yZC00NTY=